# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ROI_label_window_dark.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveROI(object):
    def setupUi(self, SaveROI):
        SaveROI.setObjectName("SaveROI")
        SaveROI.resize(590, 462)
        SaveROI.setStyleSheet("background-color: rgb(28, 29, 73);\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(SaveROI)
        self.label.setGeometry(QtCore.QRect(180, 30, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button_save_one_ROI = QtWidgets.QPushButton(SaveROI)
        self.button_save_one_ROI.setGeometry(QtCore.QRect(250, 400, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_save_one_ROI.setFont(font)
        self.button_save_one_ROI.setStyleSheet("background-color: rgb(0, 0, 100);")
        self.button_save_one_ROI.setObjectName("button_save_one_ROI")
        self.scrollArea = QtWidgets.QScrollArea(SaveROI)
        self.scrollArea.setGeometry(QtCore.QRect(90, 90, 441, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 439, 279))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        self.retranslateUi(SaveROI)
        QtCore.QMetaObject.connectSlotsByName(SaveROI)

    def retranslateUi(self, SaveROI):
        _translate = QtCore.QCoreApplication.translate
        SaveROI.setWindowTitle(_translate("SaveROI", "Dialog"))
        self.label.setText(_translate("SaveROI", "Choose the label of ROI:"))
        self.button_save_one_ROI.setText(_translate("SaveROI", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveROI = QtWidgets.QDialog()
    ui = Ui_SaveROI()
    ui.setupUi(SaveROI)
    SaveROI.show()
    sys.exit(app.exec_())
