# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'save_windows_dark.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_save(object):
    def setupUi(self, save):
        save.setObjectName("save")
        save.resize(271, 140)
        save.setStyleSheet("background-color: rgb(28, 29, 73);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_OK = QtWidgets.QPushButton(save)
        self.pushButton_OK.setGeometry(QtCore.QRect(90, 90, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton_OK.setFont(font)
        self.pushButton_OK.setStyleSheet("background-color: rgb(0, 0, 100);")
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.label = QtWidgets.QLabel(save)
        self.label.setGeometry(QtCore.QRect(50, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(save)
        QtCore.QMetaObject.connectSlotsByName(save)

    def retranslateUi(self, save):
        _translate = QtCore.QCoreApplication.translate
        save.setWindowTitle(_translate("save", "Dialog"))
        self.pushButton_OK.setText(_translate("save", "OK"))
        self.label.setText(_translate("save", "Save sucessful!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    save = QtWidgets.QDialog()
    ui = Ui_save()
    ui.setupUi(save)
    save.show()
    sys.exit(app.exec_())
