# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload_video_window_dark.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UploadVideo(object):
    def setupUi(self, UploadVideo):
        UploadVideo.setObjectName("UploadVideo")
        UploadVideo.resize(329, 131)
        UploadVideo.setStyleSheet("background-color: rgb(28, 29, 73);\n"
"color: rgb(255, 255, 255);")
        self.textBrowser = QtWidgets.QTextBrowser(UploadVideo)
        self.textBrowser.setGeometry(QtCore.QRect(40, 40, 261, 51))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(UploadVideo)
        QtCore.QMetaObject.connectSlotsByName(UploadVideo)

    def retranslateUi(self, UploadVideo):
        _translate = QtCore.QCoreApplication.translate
        UploadVideo.setWindowTitle(_translate("UploadVideo", "Dialog"))
        self.textBrowser.setHtml(_translate("UploadVideo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Upload video ...</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UploadVideo = QtWidgets.QDialog()
    ui = Ui_UploadVideo()
    ui.setupUi(UploadVideo)
    UploadVideo.show()
    sys.exit(app.exec_())
